### ISSUE TITLE
udd uses deprecated features

### ISSUE THREAD

**Issue by e-kwsm** [hayd/deno-udd#113]
udd: 09f9994e2588a0744b8983f91122932b494eb176

```shellsession
$ deno --version
deno 2.1.2 (stable, release, x86_64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2
```

```shellsession
$ deno lint
error[no-deprecated-deno-api]: `Deno.run` was removed in Deno 2. See the Deno 1.x to 2.x Migration Guide for further details: https://docs.deno.com/runtime/reference/migrate_deprecations/
  --> /tmp/deno-udd/main.ts:12:17
   | 
12 |       const p = Deno.run({
   |                 ^^^^^^^^
   = hint: Use `Deno.Command` from https://deno.land/api?s=Deno.Command instead

  docs: https://lint.deno.land/rules/no-deprecated-deno-api


error[no-deprecated-deno-api]: `Deno.run` was removed in Deno 2. See the Deno 1.x to 2.x Migration Guide for further details: https://docs.deno.com/runtime/reference/migrate_deprecations/
  --> /tmp/deno-udd/main.ts:61:19
   | 
61 |   const process = Deno.run({
   |                   ^^^^^^^^
   = hint: Use `Deno.Command` from https://deno.land/api?s=Deno.Command instead

  docs: https://lint.deno.land/rules/no-deprecated-deno-api


Found 2 problems
Checked 12 files
```

```shellsession
$ deno test --allow-read --allow-write
Check file:///tmp/deno-udd/registry_test.ts
Check file:///tmp/deno-udd/search_test.ts
Check file:///tmp/deno-udd/semver_test.ts
Check file:///tmp/deno-udd/test.ts
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'Writer'.
  writer: Deno.Writer;
               ~~~~~~
    at file:///tmp/deno-udd/progress.ts:11:16

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'Writer'.
  constructor(n: number, writer: Deno.Writer = Deno.stdout) {
                                      ~~~~~~
    at file:///tmp/deno-udd/progress.ts:13:39

TS4114 [ERROR]: This member must have an 'override' modifier because it overrides a member in the base class 'Progress'.
  async log(_: string) {}
        ~~~
    at file:///tmp/deno-udd/progress.ts:26:9

TS4114 [ERROR]: This member must have an 'override' modifier because it overrides a member in the base class 'DenoLand'.
  async all(): Promise<string[]> {
        ~~~
    at file:///tmp/deno-udd/test_deps.ts:37:9

Found 4 errors.
```

**Comment by e-kwsm** [comment]
https://lint.deno.land/rules/no-deprecated-deno-api

- `Deno.run` is deprecated since [v1.31](https://deno.com/blog/v1.31#api-stabilizations)
- `Deno.Writer` deprecated since [v1.39](https://deno.com/blog/v1.39#deprecated-io-interfaces)

**Comment by e-kwsm** [comment]
- [std/flags is deprecated since 0.207.0](https://deno.land/std@0.207.0/flags/mod.ts) and [std/cli](https://deno.land/std/cli/mod.ts) should be used instead
- [std/testing/asserts is deprecated since 0.195.0](https://deno.land/std@0.195.0/testing/asserts.ts) and [std/assert](https://deno.land/std/assert) should be used instead
