### ISSUE TITLE
Getting syntax error

### ISSUE THREAD

**Issue by mwoodpatrick** [hayd/deno-udd#22]
I'm getting the following syntax error when running on the files from:

   https://github.com/fhsinchy/deno-blog 

find . -name "*.ts" -exec udd {} \;
./routes/blogs.ts
./routes/home.ts
./routes/auth.ts
./tests/version.test.ts
./db/mysql.ts
./helpers/between.ts
./controllers/blogs.ts
./controllers/auth.ts
./middleware/logger.ts
./middleware/authorize.ts
./middleware/timer.ts
./middleware/error.ts
./app.ts
./models/User.ts
./models/Blog.ts
./bin/server.ts
./deps.ts
[1/6] Looking for releases: https://deno.land/x/mysql@2.1.0/mod.tserror: Uncaught SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at Response.json ($deno$/web/body.ts:183:17)
    at async DenoLand.all (https://deno.land/x/udd@0.2.0/registry.ts:109:20)
    at async Udd.update (https://deno.land/x/udd@0.2.0/mod.ts:82:22)
    at async Udd.run (https://deno.land/x/udd@0.2.0/mod.ts:69:22)
    at async udd (https://deno.land/x/udd@0.2.0/mod.ts:14:10)
    at async main (https://deno.land/x/udd@0.2.0/main.ts:84:21)
    at async https://deno.land/x/udd@0.2.0/main.ts:124:3
./debug_deno.ts
[1/1] Using latest: https://deno.land/std@v0.62.0/path/posix.ts
Already latest version:
https://deno.land/std@v0.62.0/path/posix.ts == v0.62.0

**Comment by rclarey** [comment]
Try updating to version 0.3.0
`deno install -A -f -n udd https://deno.land/x/udd@0.3.0/main.ts`

The `deno.land/x/` registry database file was moved in the [deno_website2](https://github.com/denoland/deno_website2) repo at some point, breaking older versions of udd. Release 0.3.0 fixes this

**Comment by mwoodpatrick** [comment]
Many thanks,  that worked

**Comment by mwoodpatrick** [comment]
I'm running with udd@0.3.0 on wsl2 and this had been working fine but today I started to get the error below any suggestions at to what the error is or best way to debug?

udd deps.ts
deps.ts
[1/8] Looking for releases: https://deno.land/x/mysql@v2.3.0/mod.tserror: Uncaught SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at Response.json ($deno$/web/body.ts:183:17)
    at async DenoLand.all (https://deno.land/x/udd@0.3.0/registry.ts:114:20)
    at async Udd.update (https://deno.land/x/udd@0.3.0/mod.ts:82:22)
    at async Udd.run (https://deno.land/x/udd@0.3.0/mod.ts:69:22)
    at async udd (https://deno.land/x/udd@0.3.0/mod.ts:14:10)
    at async main (https://deno.land/x/udd@0.3.0/main.ts:84:21)
    at async https://deno.land/x/udd@0.3.0/main.ts:124:3

**Comment by rclarey** [comment]
@mwoodpatrick it seems [deno has redone their registry](https://deno.land/posts/registry2) as of a few days ago which again breaks udd.

#24 is the issue that is tracking the fix for this.

**Comment by hayd** [comment]
@mwoodpatrick Can you try with 0.4.0?
