### ISSUE TITLE
Crashes on URLs in docs

### ISSUE THREAD

**Issue by KnorpelSenf** [hayd/deno-udd#78]
I have a file that contains JSDoc for a library. `udd` cannot operate on the file, as it tries to analyse the docs.

```
[1/1] Looking for releases: https://deno.land/x/redis) library.
   * @description The type of storage to use for keeping track of users and their requests.
   */
  storageClient?: error: Uncaught (in promise) Error: error getting versions for redis) library.
   * 
      throw new Error(`error getting versions for ${name}`);
            ^
    at DenoLand.all (https://deno.land/x/udd@0.5.0/registry.ts:130:13)
    at async Udd.update (https://deno.land/x/udd@0.5.0/mod.ts:83:22)
    at async Udd.run (https://deno.land/x/udd@0.5.0/mod.ts:70:22)
    at async udd (https://deno.land/x/udd@0.5.0/mod.ts:14:10)
    at async main (https://deno.land/x/udd@0.5.0/main.ts:84:21)
    at async https://deno.land/x/udd@0.5.0/main.ts:124:3
```

**Comment by KnorpelSenf** [comment]
Source is here: https://github.com/grammyjs/rateLimiter/blob/00cde769de6e48b11dfcdd4f7d503b57b6f43211/src/typesAndDefaults.ts#L37

**Comment by ndm13** [comment]
This looks like the same issue as #86

**Comment by KnorpelSenf** [comment]
Yes, they opened a duplicate of this issue.

**Comment by ndm13** [comment]
Well, moreso that solving that issue will also solve this one.  This looks like a specific parsing issue while that is a general one.

**Comment by KnorpelSenf** [comment]
I honestly don't see the difference, both issues are reporting that URLs in comments should be handled. Wouldn't fixing this issue also solve that one?

**Comment by masx200** [comment]
Is it possible to solve this problem with the `deno info` command?

**Comment by KnorpelSenf** [comment]
Can you elaborate?

**Comment by masx200** [comment]
https://github.com/hayd/deno-udd/issues/8

**Comment by KnorpelSenf** [comment]
Yes, that sounds like a good solution
